### ISSUE TITLE
Calling attribute_value in one line raises StaleElementReferenceError in another line

### ISSUE THREAD

**Issue by vgm106** [watir/watir-webdriver#237]
In the following piece of code, StaleElementReferenceError is raised in 'puts link.text' in presence of the next line. If even one of those two lines were commented the loop would complete without error. I isolated this error to attribute_value method.

```ruby
    @searchResultsFrame.links.each do |link|         //loop through links in an iframe
              puts link.text
              puts @browser.div(:id => "SearchResultsTabFrame").attribute_value("style")
              puts "hello world"       
    end
```

```
C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/response.rb:51:in `assert_ok': Modal dialog present (Selenium::W
ebDriver::Error::UnhandledAlertError)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/bridge.rb:634:in `raw_execute'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/bridge.rb:612:in `execute'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/remote/bridge.rb:580:in `find_element_by'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/selenium-webdriver-2.39.0/lib/selenium/webdriver/common/search_context.rb:42:in `find_element'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.6.4/lib/watir-webdriver/elements/frame.rb:120:in `method_missing'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.6.4/lib/watir-webdriver/locators/element_locator.rb:251:in `by_id'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.6.4/lib/watir-webdriver/locators/element_locator.rb:26:in `locate'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.6.4/lib/watir-webdriver/elements/element.rb:509:in `locate'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.6.4/lib/watir-webdriver/elements/element.rb:487:in `assert_exists'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/watir-webdriver-0.6.4/lib/watir-webdriver/row_container.rb:33:in `strings'
        from c:/Users/ganesm1/My Documents/Fusion_POP/features/pages/search_results.rb:47:in `getSearchResultsTable'
        from excel_reader.rb:52:in `block in <main>'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/spreadsheet-0.9.6/lib/spreadsheet/worksheet.rb:147:in `block in each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/spreadsheet-0.9.6/lib/spreadsheet/worksheet.rb:146:in `upto'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/spreadsheet-0.9.6/lib/spreadsheet/worksheet.rb:146:in `each'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/spreadsheet-0.9.6/lib/spreadsheet/excel/worksheet.rb:47:in `each'
        from excel_reader.rb:36:in `<main>'
```

**Comment by jarib** [comment]
This should be fixed by the above merged PRs and work OK in the next release.
