### ISSUE TITLE
Utilizing Extension select_text gives error: a is undefined

### ISSUE THREAD

**Issue by dmhalejr** [watir/watir-webdriver#313]
**Gemfile.lock:**
```
selenium-webdriver (2.44.0)
 childprocess (~> 0.5)
 multi_json (~> 1.0)
 rubyzip (~> 1.0)
 websocket (~> 1.0)
watir-webdriver (0.6.11)
 selenium-webdriver (>= 2.18.0)
```
**Simple Example:**
```
require 'watir-webdriver'
require 'watir-webdriver/extensions/select_text'
b = Watir::Browser.new :firefox
b.goto 'www.google.com'
b.element(:css => 'input#gbqfq').send_keys "some test"
b.element(:css => 'button#gbqfb').submit
b.element(:css => 'span.st').select_text 'Pre-test'
```
**Error:**
```
Selenium::WebDriver::Error::JavascriptError: a is undefined
	from [remote server] https://www.google.com/?gws_rd=ssl#q=some+test line 68 > Function:26:in `F'
	from [remote server] https://www.google.com/?gws_rd=ssl#q=some+test line 68 > Function:39:in `Eb'
	from [remote server] https://www.google.com/?gws_rd=ssl#q=some+test line 68 > Function:50:in `T'
	from [remote server] https://www.google.com/?gws_rd=ssl#q=some+test line 68 > Function:60:in `Db'
	from [remote server] https://www.google.com/?gws_rd=ssl#q=some+test line 68 > Function:61:in `dc'
	from [remote server] https://www.google.com/?gws_rd=ssl#q=some+test line 68 > Function:61:in `anonymous/</<'
	from [remote server] https://www.google.com/?gws_rd=ssl#q=some+test line 68 > Function:14:in `anonymous/<'
	from [remote server] https://www.google.com/?gws_rd=ssl#q=some+test line 68 > Function:14:in `anonymous'
	from [remote server] https://www.google.com/?gws_rd=ssl#q=some+test:68:in `handleEvaluateEvent'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:339:in `executeScript'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:193:in `execute_script'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/watir-webdriver-0.6.11/lib/watir-webdriver/atoms.rb:20:in `execute_atom'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/watir-webdriver-0.6.11/lib/watir-webdriver/extensions/select_text.rb:7:in `select_text'
```

**Comment by titusfortner** [comment]
This is a [known issue](https://code.google.com/p/selenium/issues/detail?id=8390) with Firefox 35. The fix is committed in master and will be available with the next watir release, which is dependent on the next selenium-webdriver release (no ETA).

**Comment by dmhalejr** [comment]
@titusfortner Thanks for the clarification! Now... patience

**Comment by p0deje** [comment]
@dmhalejr To make it clear, that's not the issue with watir-webdriver, but the problem with selenium-webdriver.

**Comment by dmhalejr** [comment]
@p0deje Thanks for the clarification. I'll make sure to assess any issues I may run into here https://code.google.com/p/selenium/issues/list before opening up superfluous issues here :smile:
