### ISSUE TITLE
Utilizing .flash returns arguments[0] is undefined

### ISSUE THREAD

**Issue by dmhalejr** [watir/watir-webdriver#314]
**Gemfile.lock** 
    selenium-webdriver (2.44.0)
      childprocess (~> 0.5)
      multi_json (~> 1.0)
      rubyzip (~> 1.0)
      websocket (~> 1.0)
    watir-webdriver (0.6.11)
      selenium-webdriver (>= 2.18.0)
**Simple Example:**
```
require 'watir-webdriver'
b = Watir::Browser.new :firefox
b.goto 'www.google.com' 
b.img(:id => 'hplogo').flash
```

**Error:**
```
Selenium::WebDriver::Error::JavascriptError: arguments[0] is undefined
	from [remote server] https://www.google.com/?gws_rd=ssl line 68 > Function:1:in `anonymous'
	from [remote server] https://www.google.com/?gws_rd=ssl:68:in `handleEvaluateEvent'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:339:in `executeScript'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:193:in `execute_script'
	from /Users/dhale/.rvm/gems/ruby-2.1.0/gems/watir-webdriver-0.6.11/lib/watir-webdriver/elements/element.rb:234:in `flash'
	from (irb):5
	from /Users/dhale/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'
```

**Comment by titusfortner** [comment]
Anything with execute_script will not work with Firefox 35, until selenium-webdriver 2.45 is released. See #313
