### ISSUE TITLE
Unable to create Browser when HTTP_PROXY environment variable is set

### ISSUE THREAD

**Issue by karlosmid** [watir/watir-webdriver#319]
Ruby version: 2.1.2
watir-webdriver version: 0.6.11
selenium-webdriver version 2.44.0

Replication steps:
`>irb`
`2.1.2 :001> require 'watir-webdriver'`
`2.1.2 :002> ENV['HTTP_PROXY'] =''`
`2.1.2 :003> b = Watir::Browser.new`
```firefox launches, it is running for some time, then it is automatically closed. After that, exception is logged in console```  

Additional info:
I was able to replicate issue using `ENV['http_proxy']`  
I was not able to replicate issue using `ENV['ftp_proxy']` and `ENV['https_proxy']`  

Here is exception stack:
```
URI::InvalidURIError: bad URI(absolute but no path): http://
	from /Users/karlosmid/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:146:in `split'
	from /Users/karlosmid/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:211:in `parse'
	from /Users/karlosmid/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/uri/common.rb:747:in `parse'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:92:in `new_http_client'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:17:in `http'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:83:in `response_for'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:39:in `request'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:101:in `create_session'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:68:in `initialize'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/firefox/bridge.rb:36:in `initialize'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `new'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/driver.rb:31:in `for'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver.rb:67:in `for'
	from /Users/karlosmid/.rvm/gems/ruby-2.1.2@lawfirmmatrix/gems/watir-webdriver-0.6.11/lib/watir-webdriver/browser.rb:46:in `initialize'
	from (irb):7:in `new'
```

**Comment by titusfortner** [comment]
[This is a feature, not a bug.](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/http/default.rb#L101)
ENV['HTTP_PROXY'] is what Selenium uses to send the processes through a running proxy that you've set up.
It is expecting the value to be nil or to have an url in it. An empty string should cause it to fail, as should any other string containing an invalid url.

Regardless, this is something for the selenium project, not the watir project.

**Comment by karlosmid** [comment]
From watir-webdriver documentation:
http://watirwebdriver.com/browser-proxies/

So http_proxy env variable is preceding setting proxy using browser profiles?

**Comment by titusfortner** [comment]
I'm not all that familiar with the proxy code since I've never used it. I'm not sure how the precedence works, just that it can't be an empty string for what you were running.

**Comment by p0deje** [comment]
The point is that `HTTP_PROXY` is used as a proxy for communicating via wire protocol (i.e. from selenium client to selenium server). That's probably not what you want to achieve, so just get rid to env variable and configure browser proxy instead.

**Comment by karlosmid** [comment]
Thanks @p0deje for clarification!
I also noted possible issue for different values of http_proxy, I will post that to selenium project.

Regards, Karlo.
