### ISSUE TITLE
Appium on iOS Safari real device + Watir

### ISSUE THREAD

**Issue by lluisTypeform** [watir/watir-webdriver#389]
Hello,

We are able to use Watir with Appium on Android devices, but one thing does not functions is to use  the element locator on iOS devices.
We are able to start the Safari browser and go to the desried page, but we ere not able to interact with the elements on the page loaded.

Once we try something like: browser.text_field(id: 'lst-ib').set('Appium') , Appium fails with "Selenium::WebDriver::Error::UnknownError: ERROR running Appium command: Cannot read property 'send' of null"

Here is how we start our tests:

```
ios_webkit: "/usr/local/lib/node_modules/appium/bin/ios-webkit-debug-proxy-launcher.js -c #{@device_udid}:27753"
appium_server: "appium --address 127.0.0.1 --port 4723 --udid #{@device_udid} --native-instruments-lib"

appium.txt:
[caps]
platformName = "ios"
deviceName = ""
browserName = "Safari"

[appium_lib]
sauce_username = false
sauce_access_key = false
```

Small exmple of our code:

```
require 'rubygems'
require 'appium_lib'

caps = Appium.load_appium_txt file: File.join(File.absolute_path(File.join(get_browsers_and_devices_path, 'appium.txt'))), verbose: true

appium_driver = Appium::Driver.new(caps)
driver = appium_driver.start_driver
Appium.promote_appium_methods Object
browser = Watir::Browser.new driver

browser.goto('http://www.google.com')

browser.text_field(id: 'lst-ib').set('Appium')

browser.button(name: 'btnK').click

browser.quit
```

Here the log of what happens once we try write on the input:

```
info: --> GET /wd/hub/session/858be990-8c38-4b4c-b9a8-4b2d1e00bc06/window_handle {}
info: [debug] Responding to client with success: {"status":0,"value":"1","sessionId":"858be990-8c38-4b4c-b9a8-4b2d1e00bc06"}
info: <-- GET /wd/hub/session/858be990-8c38-4b4c-b9a8-4b2d1e00bc06/window_handle 200 3.943 ms - 75 {"status":0,"value":"1","sessionId":"858be990-8c38-4b4c-b9a8-4b2d1e00bc06"}
info: --> GET /wd/hub/session/858be990-8c38-4b4c-b9a8-4b2d1e00bc06/window_handles {}
info: [debug] [REMOTE] Getting WebKitRemoteDebugger pageArray
info: [debug] Responding to client with success: {"status":0,"value":["1"],"sessionId":"858be990-8c38-4b4c-b9a8-4b2d1e00bc06"}
info: <-- GET /wd/hub/session/858be990-8c38-4b4c-b9a8-4b2d1e00bc06/window_handles 200 4.601 ms - 77 {"status":0,"value":["1"],"sessionId":"858be990-8c38-4b4c-b9a8-4b2d1e00bc06"}
info: --> POST /wd/hub/session/858be990-8c38-4b4c-b9a8-4b2d1e00bc06/frame {"id":null}
info: [debug] Leaving web frame and going back to default content
info: [debug] Responding to client with success: {"status":0,"value":"","sessionId":"858be990-8c38-4b4c-b9a8-4b2d1e00bc06"}
info: <-- POST /wd/hub/session/858be990-8c38-4b4c-b9a8-4b2d1e00bc06/frame 200 2.041 ms - 74 {"status":0,"value":"","sessionId":"858be990-8c38-4b4c-b9a8-4b2d1e00bc06"}
info: --> POST /wd/hub/session/858be990-8c38-4b4c-b9a8-4b2d1e00bc06/element {"using":"id","value":"lst-ib"}
info: [debug] Waiting up to 0ms for condition
info: [debug] [REMOTE] Executing 'find_element' atom in default context
info: [debug] [REMOTE] Sending javascript command
info: [debug] [REMOTE] Remote debugger data sent [{"method":"Runtime.evaluate","params":{"objectGroup":"console","includeCommandLineAPI":true,"doNotPauseOnExceptionsAndMuteConsole":true,"expression":"(function(){return function(){function h(a){return...]
info: <-- POST /wd/hub/session/858be990-8c38-4b4c-b9a8-4b2d1e00bc06/element 500 10.906 ms - 89 

Selenium::WebDriver::Error::UnknownError: ERROR running Appium command: Cannot read property 'send' of null
./features/step_definitions/mobile_steps.rb:5:in `/^I sign up in Android mobile$/'
./features/acceptance/mobile/appium_tests.feature:6:in `When I sign up in Android mobile'
TypeError: Cannot read property 'send' of null
    at [object Object].WebKitRemoteDebugger.send (/usr/local/lib/node_modules/appium/lib/devices/ios/webkit-remote-debugger.js:168:14)
    at [object Object].RemoteDebugger.execute (/usr/local/lib/node_modules/appium/lib/devices/ios/remote-debugger.js:367:10)
    at [object Object].RemoteDebugger.executeAtom (/usr/local/lib/node_modules/appium/lib/devices/ios/remote-debugger.js:298:8)
    at [object Object].iOSController.executeAtom (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:662:15)
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:321:10)
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/common.js:90:13)
    at [object Object].<anonymous> (/usr/local/lib/node_modules/appium/lib/devices/common.js:66:5)
    at [object Object].exports.waitForCondition (/usr/local/lib/node_modules/appium/lib/devices/common.js:81:3)
    at [object Object].exports.implicitWaitForCondition (/usr/local/lib/node_modules/appium/lib/devices/common.js:92:8)
    at [object Object].iOSController.findWebElementOrElements (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:325:8)
    at [object Object].iOSController.findElementOrElements (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:331:12)
    at [object Object].iOSController.findElement (/usr/local/lib/node_modules/appium/lib/devices/ios/ios-controller.js:339:8)
    at exports.findElement (/usr/local/lib/node_modules/appium/lib/server/controller.js:274:16)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:340:14)
    at param (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:356:14)
    at Function.proto.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:400:3)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at exports.sessionBeforeFilter (/usr/local/lib/node_modules/appium/lib/server/controller.js:56:5)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:110:13)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:104:14)
    at Route.dispatch (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:91:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/layer.js:82:5)
    at /usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:267:22
    at Function.proto.process_params (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:321:12)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/index.js:261:10)
    at next (/usr/local/lib/node_modules/appium/node_modules/express/lib/router/route.js:100:14)
info: --> GET /wd/hub/session/858be990-8c38-4b4c-b9a8-4b2d1e00bc06/screenshot {}
info: [debug] Pushing command to appium work queue: "au.getScreenOrientation()"
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
```

----

Just to let you know, if we try to interact with elements on the borwser in Selenium style, not Watir, there is no problem. Seems that is just a problem with Watir.
Example:

```
$driver.find_element(id: 'lst-ib').send_keys('Appium')
```

Thanks a lot for any advice you could provide us.

**Comment by titusfortner** [comment]
I believe this is your issue here: https://github.com/appium/appium/issues/4499
I'm not familiar enough with it to know why it would be affecting your Watir implementation and not your Selenium one, since the underlying commands are the same.

**Comment by lluisTypeform** [comment]
Thanks @titusfortner 

I'm afraid the problem we are issuing is different.
On the thread you have pointed out talks a problem with the iOS webkit:
```
Invalid message _rpc_applicationUpdated: 
WIRApplicationBundleIdentifierKey
com.apple.WebKit.WebContent
WIRHostApplicationIdentifierKey
PID:1601
WIRApplicationNameKey
```
but on our case this service does not show any error.

On the moment we execute:
```
browser.text_field(id: 'lst-ib').set('Appium')
```
We have on the webkit:
```
ss.accept server=4 new_client=8
ss.add_fd(8)
ss.recv fd=8 len=64
ws.recv[64]:
 47 45 54 20 2F 6A 73 6F 6E 20 48 54 54 50 2F 31 2E 31 0D  GET /json HTTP/1.1.
 0A                                                        .
 48 6F 73 74 3A 20 6C 6F 63 61 6C 68 6F 73 74 3A 32 37 37  Host: localhost:277
 35 33 0D 0A                                               53..
 43 6F 6E 6E 65 63 74 69 6F 6E 3A 20 63 6C 6F 73 65 0D 0A  Connection: close..
 0D 0A                                                     ..
ss.remove_fd(8)
```
Then Appium writes the same line for a couple of minutes:
```
info: [debug] We're in the middle of processing a remote debugger command, waiting to run next command until done
```
Finally it stops "trying" and on the Webkit does not show any error:
```
ss.recv fd=6 len=450
wi.recv[450]:
 00 00 01 BE 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57  ....bplist00..._..W
 49 52 46 69 6E 61 6C 4D 65 73 73 61 67 65 4B 65 79 4F 11  IRFinalMessageKeyO.
 01 74 62 70 6C 69 73 74 30 30 D2 01 02 03 10 5A 5F 5F 61  .tbplist00.....Z__a
 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63 74 6F 72 D6  rgumentZ__selector.
 04 05 06 07 08 09 0A                                      .......
 0B 0C 0D 0E 0F 5F 10 1B 57 49 52 41 70 70 6C 69 63 61 74  ....._..WIRApplicat
 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79 5F 10 18  ionIdentifierKey_..
 57 49 52 49 73 41 70 70 6C 69 63 61 74 69 6F 6E 50 72 6F  WIRIsApplicationPro
 78 79 4B 65 79 5F 10 15 57 49 52 41 70 70 6C 69 63 61 74  xyKey_..WIRApplicat
 69 6F 6E 4E 61 6D 65 4B 65 79 5F 10 21 57 49 52 41 70 70  ionNameKey_.!WIRApp
 6C 69 63 61 74 69 6F 6E 42 75 6E 64 6C 65 49 64 65 6E 74  licationBundleIdent
 69 66 69 65 72 4B 65 79 5F 10 19 57 49 52 49 73 41 70 70  ifierKey_..WIRIsApp
 6C 69 63 61 74 69 6F 6E 41 63 74 69 76 65 4B 65 79 5F 10  licationActiveKey_.
 1F 57 49 52 48 6F 73 74 41 70 70 6C 69 63 61 74 69 6F 6E  .WIRHostApplication
 49 64 65 6E 74 69 66 69 65 72 4B 65 79 58 50 49 44 3A 31  IdentifierKeyXPID:1
 37 35 34 09 50 5F 10 1B 63 6F 6D 2E 61 70 70 6C 65 2E 57  754.P_..com.apple.W
 65 62 4B 69 74 2E 57 65 62 43 6F 6E 74 65 6E 74 10 00 58  ebKit.WebContent..X
 50 49 44 3A 31 37 34 33 5F 10 18 5F 72 70 63 5F 61 70 70  PID:1743_.._rpc_app
 6C 69 63 61 74 69 6F 6E 55 70 64 61 74 65 64 3A 00 08 00  licationUpdated:...
 0D 00 18 00 23 00 30 00 4E 00 69 00 81 00 A5 00 C1 00 E3  ....#.0.N.i........
 00 EC 00 ED 00 EE 01 0C 01 0E 01 17 00 00 00 00 00 00 02  ...................
 01 00 00 00 00 00 00 00 11 00 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 01 32 00 08 00 0B 00 20 00 00 00 00 00 00 02  .....2..... .......
 01 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 01 98                                         ......
wi.recv_packet[450]:
 00 00 01 BE 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57  ....bplist00..._..W
 49 52 46 69 6E 61 6C 4D 65 73 73 61 67 65 4B 65 79 4F 11  IRFinalMessageKeyO.
 01 74 62 70 6C 69 73 74 30 30 D2 01 02 03 10 5A 5F 5F 61  .tbplist00.....Z__a
 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63 74 6F 72 D6  rgumentZ__selector.
 04 05 06 07 08 09 0A                                      .......
 0B 0C 0D 0E 0F 5F 10 1B 57 49 52 41 70 70 6C 69 63 61 74  ....._..WIRApplicat
 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79 5F 10 18  ionIdentifierKey_..
 57 49 52 49 73 41 70 70 6C 69 63 61 74 69 6F 6E 50 72 6F  WIRIsApplicationPro
 78 79 4B 65 79 5F 10 15 57 49 52 41 70 70 6C 69 63 61 74  xyKey_..WIRApplicat
 69 6F 6E 4E 61 6D 65 4B 65 79 5F 10 21 57 49 52 41 70 70  ionNameKey_.!WIRApp
 6C 69 63 61 74 69 6F 6E 42 75 6E 64 6C 65 49 64 65 6E 74  licationBundleIdent
 69 66 69 65 72 4B 65 79 5F 10 19 57 49 52 49 73 41 70 70  ifierKey_..WIRIsApp
 6C 69 63 61 74 69 6F 6E 41 63 74 69 76 65 4B 65 79 5F 10  licationActiveKey_.
 1F 57 49 52 48 6F 73 74 41 70 70 6C 69 63 61 74 69 6F 6E  .WIRHostApplication
 49 64 65 6E 74 69 66 69 65 72 4B 65 79 58 50 49 44 3A 31  IdentifierKeyXPID:1
 37 35 34 09 50 5F 10 1B 63 6F 6D 2E 61 70 70 6C 65 2E 57  754.P_..com.apple.W
 65 62 4B 69 74 2E 57 65 62 43 6F 6E 74 65 6E 74 10 00 58  ebKit.WebContent..X
 50 49 44 3A 31 37 34 33 5F 10 18 5F 72 70 63 5F 61 70 70  PID:1743_.._rpc_app
 6C 69 63 61 74 69 6F 6E 55 70 64 61 74 65 64 3A 00 08 00  licationUpdated:...
 0D 00 18 00 23 00 30 00 4E 00 69 00 81 00 A5 00 C1 00 E3  ....#.0.N.i........
 00 EC 00 ED 00 EE 01 0C 01 0E 01 17 00 00 00 00 00 00 02  ...................
 01 00 00 00 00 00 00 00 11 00 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 01 32 00 08 00 0B 00 20 00 00 00 00 00 00 02  .....2..... .......
 01 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 01 98                                         ......
ss.recv fd=6 len=4
wi.recv[4]:
 00 00 01 8E                                               ....
ss.recv fd=6 len=398
wi.recv[398]:
 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57 49 52 46 69  bplist00..._..WIRFi
 6E 61 6C 4D 65 73 73 61 67 65 4B 65 79 4F 11 01 44 62 70  nalMessageKeyO..Dbp
 6C 69 73 74 30 30 D2 01 02 03 0E 5A 5F 5F 61 72 67 75 6D  list00.....Z__argum
 65 6E 74 5A 5F 5F 73 65 6C 65 63 74 6F 72 D5 04 05 06 07  entZ__selector.....
 08 09 0A                                                  ...
 0B 0C 0D 5F 10 1B 57 49 52 41 70 70 6C 69 63 61 74 69 6F  ..._..WIRApplicatio
 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79 5F 10 18 57 49  nIdentifierKey_..WI
 52 49 73 41 70 70 6C 69 63 61 74 69 6F 6E 50 72 6F 78 79  RIsApplicationProxy
 4B 65 79 5F 10 15 57 49 52 41 70 70 6C 69 63 61 74 69 6F  Key_..WIRApplicatio
 6E 4E 61 6D 65 4B 65 79 5F 10 21 57 49 52 41 70 70 6C 69  nNameKey_.!WIRAppli
 63 61 74 69 6F 6E 42 75 6E 64 6C 65 49 64 65 6E 74 69 66  cationBundleIdentif
 69 65 72 4B 65 79 5F 10 19 57 49 52 49 73 41 70 70 6C 69  ierKey_..WIRIsAppli
 63 61 74 69 6F 6E 41 63 74 69 76 65 4B 65 79 58 50 49 44  cationActiveKeyXPID
 3A 31 37 34 33 08 56 53 61 66 61 72 69 5F 10 16 63 6F 6D  :1743.VSafari_..com
 2E 61 70 70 6C 65 2E 6D 6F 62 69 6C 65 73 61 66 61 72 69  .apple.mobilesafari
 10 00 5F 10 18 5F 72 70 63 5F 61 70 70 6C 69 63 61 74 69  .._.._rpc_applicati
 6F 6E 55 70 64 61 74 65 64 3A 00 08 00 0D 00 18 00 23 00  onUpdated:.......#.
 2E 00 4C 00 67 00 7F 00 A3 00 BF 00 C8 00 C9 00 D0 00 E9  ..L.g..............
 00 EB 00 00 00 00 00 00 02 01 00 00 00 00 00 00 00 0F 00  ...................
 00 00 00 00 00 00 00 00 00 00 00 00 00 01 06 00 08 00 0B  ...................
 00 20 00 00 00 00 00 00 02 01 00 00 00 00 00 00 00 03 00  . .................
 00 00 00 00 00 00 00 00 00 00 00 00 00 01 68              ..............h
wi.recv_packet[402]:
 00 00 01 8E 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57  ....bplist00..._..W
 49 52 46 69 6E 61 6C 4D 65 73 73 61 67 65 4B 65 79 4F 11  IRFinalMessageKeyO.
 01 44 62 70 6C 69 73 74 30 30 D2 01 02 03 0E 5A 5F 5F 61  .Dbplist00.....Z__a
 72 67 75 6D 65 6E 74 5A 5F 5F 73 65 6C 65 63 74 6F 72 D5  rgumentZ__selector.
 04 05 06 07 08 09 0A                                      .......
 0B 0C 0D 5F 10 1B 57 49 52 41 70 70 6C 69 63 61 74 69 6F  ..._..WIRApplicatio
 6E 49 64 65 6E 74 69 66 69 65 72 4B 65 79 5F 10 18 57 49  nIdentifierKey_..WI
 52 49 73 41 70 70 6C 69 63 61 74 69 6F 6E 50 72 6F 78 79  RIsApplicationProxy
 4B 65 79 5F 10 15 57 49 52 41 70 70 6C 69 63 61 74 69 6F  Key_..WIRApplicatio
 6E 4E 61 6D 65 4B 65 79 5F 10 21 57 49 52 41 70 70 6C 69  nNameKey_.!WIRAppli
 63 61 74 69 6F 6E 42 75 6E 64 6C 65 49 64 65 6E 74 69 66  cationBundleIdentif
 69 65 72 4B 65 79 5F 10 19 57 49 52 49 73 41 70 70 6C 69  ierKey_..WIRIsAppli
 63 61 74 69 6F 6E 41 63 74 69 76 65 4B 65 79 58 50 49 44  cationActiveKeyXPID
 3A 31 37 34 33 08 56 53 61 66 61 72 69 5F 10 16 63 6F 6D  :1743.VSafari_..com
 2E 61 70 70 6C 65 2E 6D 6F 62 69 6C 65 73 61 66 61 72 69  .apple.mobilesafari
 10 00 5F 10 18 5F 72 70 63 5F 61 70 70 6C 69 63 61 74 69  .._.._rpc_applicati
 6F 6E 55 70 64 61 74 65 64 3A 00 08 00 0D 00 18 00 23 00  onUpdated:.......#.
 2E 00 4C 00 67 00 7F 00 A3 00 BF 00 C8 00 C9 00 D0 00 E9  ..L.g..............
 00 EB 00 00 00 00 00 00 02 01 00 00 00 00 00 00 00 0F 00  ...................
 00 00 00 00 00 00 00 00 00 00 00 00 00 01 06 00 08 00 0B  ...................
 00 20 00 00 00 00 00 00 02 01 00 00 00 00 00 00 00 03 00  . .................
 00 00 00 00 00 00 00 00 00 00 00 00 00 01 68              ..............h
wi.send_packet[289]:
 00 00 01 1D 62 70 6C 69 73 74 30 30 D1 01 02 5F 10 12 57  ....bplist00..._..W
 49 52 46 69 6E 61 6C 4D 65 73 73 61 67 65 4B 65 79 4F 10  IRFinalMessageKeyO.
 D6 62 70 6C 69 73 74 30 30 D2 01 03 02 04 5A 5F 5F 73 65  .bplist00.....Z__se
 6C 65 63 74 6F 72 5F 10 17 5F 72 70 63 5F 66 6F 72 77 61  lector_.._rpc_forwa
 72 64 47 65 74 4C 69 73 74 69 6E 67 3A 5A 5F 5F 61 72 67  rdGetListing:Z__arg
 75 6D 65 6E 74 D2 05 07 06 08 5F 10 1A 57 49 52 43 6F 6E  ument....._..WIRCon
 6E 65 63 74 69 6F 6E 49 64 65 6E 74 69 66 69 65 72 4B 65  nectionIdentifierKe
 79 5F 10 24 41 34 43 34 39 39 30 42 2D 35 45 41 41 2D 34  y_.$A4C4990B-5EAA-4
 45 31 45 2D 39 30 34 30 2D 35 43 38 30 30 46 30 35 42 37  E1E-9040-5C800F05B7
 44 30 5F 10 1B 57 49 52 41 70 70 6C 69 63 61 74 69 6F 6E  D0_..WIRApplication
 49 64 65 6E 74 69 66 69 65 72 4B 65 79 58 50 49 44 3A 31  IdentifierKeyXPID:1
 37 34 33 08 0D 18 32 3D 42 5F 86 A4 00 00 00 00 00 00 01  743...2=B_.........
 01 00 00 00 00 00 00 00 09 00 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 00 00 AD A0 08 0B 20 00 00 00 00 00 00 01 01 00  ......... .........
 00 00 00 00 00 00 03 00 00 00 00 00 00 00 00 00 00 00 00  ...................
 00 00 00 FA                                               ....
ss.recv fd=8 len=0
ss.remove_fd(8)
ss.recv fd=5 len=0
ss.remove_fd(5)
ss.recv fd=7 len=0
ss.remove_fd(7)
```

Also I have to mention that on a simulated device, same iOS version, the test runs correctly. So seems that the webkit could be the problem..
Probably I'm missing something, but actually I'm completely lost :(

And to finish say that the device is an iPhone 5 (9.2)

**Comment by titusfortner** [comment]
The problem happens after Watir calls the command to send keys. It looks like a WebKitRemoteDebugger issue (and the failure appears to be the same as in the code I linked).
```
TypeError: Cannot read property 'send' of null
    at [object Object].WebKitRemoteDebugger.send (/usr/local/lib/node_modules/appium/lib/devices/ios/webkit-remote-debugger.js:168:14)
```
It's possibly an Appium thing, as well. The ruby_lib does a lot of monkey patching to get things to work; which might explain why something is set up for Selenium in a way that Watir doesn't use. Not really sure, and definitely don't want to dig through that code. :)

**Comment by lluisTypeform** [comment]
Thanks again @titusfortner , had opened an issue on Appium: https://github.com/appium/appium/issues/5955
I hope could get iOS real devices running Safari tests using Watir :)
