### ISSUE TITLE
always has exception Net::ReadTimeout

### ISSUE THREAD

**Issue by seaify** [watir/watir-webdriver#406]
in popup firefox, the element exists, but use browser xpath to extract element, exception shows.

ap car_iframe.element(:xpath => '//*[@id="shangpai"]/select').exists?

use watir-webdriver 0.9.1, selenium-webdriver-2.48

```
"in bridge execute"
[
    [0] :getElementTagName,
    [1] {
        :id => "{58de18a2-de4f-9b4e-980b-ebf0270c512e}"
    }
]
"in http common call"
:get
#<URI::HTTP http://127.0.0.1:7057/hub/session/1db8e902-1144-a845-adc8-3b045900074b/element/%7B58de18a2-de4f-9b4e-980b-ebf0270c512e%7D/name>
nil
/Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb:158:in `rescue in rbuf_fill': Net::ReadTimeout (Net::ReadTimeout)
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb:152:in `rbuf_fill'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb:134:in `readuntil'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/protocol.rb:144:in `readline'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/response.rb:39:in `read_status_line'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http/response.rb:28:in `read_new'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1413:in `block in transport_request'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1410:in `catch'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1410:in `transport_request'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1383:in `request'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1376:in `block in request'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:853:in `start'
        from /Users/chuck/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/net/http.rb:1374:in `request'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/http/common.rb:64:in `call'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:673:in `raw_execute'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:651:in `execute'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/remote/bridge.rb:546:in `getElementTagName'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/selenium-webdriver-2.48.1/lib/selenium/webdriver/common/element.rb:87:in `tag_name'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/locators/element_locator.rb:294:in `by_id'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/locators/element_locator.rb:38:in `locate'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/iframe.rb:8:in `locate'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/iframe.rb:20:in `switch_to!'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:565:in `ensure_context'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:547:in `locate'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:505:in `assert_exists'
        from /Users/chuck/.rvm/gems/ruby-2.2.0/gems/watir-webdriver-0.9.1/lib/watir-webdriver/elements/element.rb:42:in `exists?'
        from /Users/chuck/seaify/online-products/a16472/lib/car_publisher/com58.rb:114:in `create'
        from run.rb:20:in `<main>'
```

**Comment by titusfortner** [comment]
You get Net::ReadTimeout errors when your code makes a call to the driver and it never returns anything. In this case the issue could conceivably be in either the Remote WebDriver or in the Firefox Driver. A number of updates have been made to each in the past few releases. I recommend upgrading to 2.52 and trying again. Otherwise, if you have a reproducible example, [file a bug](https://github.com/SeleniumHQ/selenium/issues/new) with the Selenium project.

**Comment by seaify** [comment]
@titusfortner 

In mac, I switch to chrome driver, it works.

if you recommend to use selenium-webdriver 2.5.2, why not

```
  s.add_dependency "selenium-webdriver", ">= 2.5.2"
```

**Comment by titusfortner** [comment]
Because there is nothing in Watir that requires that version. Selenium versions and Firefox versions currently march in step with each other. If you want to use an older version of Firefox, you might need to use an older version of Selenium, but you can still use the latest version of Watir.
