### ISSUE TITLE
Dies with Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 7055

### ISSUE THREAD

**Issue by raintonr** [watir/watir-webdriver#426]
Eg:

```
$ irb
irb(main):001:0> require "watir-webdriver"
=> true
irb(main):002:0> browser = Watir::Browser.new :firefox
Errno::ECONNREFUSED: Connection refused - connect(2) for "127.0.0.1" port 7055
	from /usr/share/ruby/net/http.rb:879:in `initialize'
	from /usr/share/ruby/net/http.rb:879:in `open'
	from /usr/share/ruby/net/http.rb:879:in `block in connect'
	from /usr/share/ruby/timeout.rb:73:in `timeout'
	from /usr/share/ruby/net/http.rb:878:in `connect'
	from /usr/share/ruby/net/http.rb:863:in `do_start'
	from /usr/share/ruby/net/http.rb:852:in `start'
	from /usr/share/ruby/net/http.rb:1375:in `request'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/remote/http/default.rb:107:in `response_for'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/remote/http/default.rb:58:in `request'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/remote/bridge.rb:649:in `raw_execute'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/remote/bridge.rb:123:in `create_session'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/remote/bridge.rb:87:in `initialize'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/firefox/bridge.rb:55:in `initialize'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/common/driver.rb:53:in `new'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver/common/driver.rb:53:in `for'
	from /home/raintonr/.gem/ruby/gems/selenium-webdriver-2.53.1/lib/selenium/webdriver.rb:84:in `for'
	from /home/raintonr/.gem/ruby/gems/watir-webdriver-0.9.1/lib/watir-webdriver/browser.rb:46:in `initialize'
	from (irb):2:in `new'
	from (irb):2
	from /usr/bin/irb:11:in `<main>'
```

This is on FC23, everything up to date:

```
$ ruby --version
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]
$ irb --version
irb 0.9.6(09/06/30)
$ firefox --version
Mozilla Firefox 47.0
```

I suspect there might be an issue in Firefox as think I can see a window flash open then instantly disappear.

**Comment by titusfortner** [comment]
https://github.com/SeleniumHQ/selenium/issues/2110

**Comment by raintonr** [comment]
Thanks for the update. In the mean time, downgrading to Firefox 41 go me going.
